VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.define "elasticsearch" do |v|
  #   v.vm.provider "docker" do |d|
  #     d.name = "elasticsearch"
  #     d.image = "orchardup/elasticsearch"
  #     d.ports = ["9200:9200"]
  #     d.vagrant_vagrantfile = "./proxy.Vagrantfile"
  #   end
  # end

  config.vm.define "postgres" do |v|
    v.vm.provider "docker" do |d|
      d.name = "postgres"
      d.image = "library/postgres"
      d.volumes = ["/data:/var/lib/postgresql/data"]
      d.ports = ["5432:5432"]
      d.env = {
        POSTGRES_USER: "brahma",
        POSTGRES_PASSWORD: "Better_to_conquer_yourself_than_others_",
        POSTGRES_DB: "brahma"
      }
      d.vagrant_vagrantfile = "./proxy.Vagrantfile"
    end
    v.vm.synced_folder "docker-entrypoint-initdb.d", "/docker-entrypoint-initdb.d"
  end

  config.vm.define "activator" do |v|
    v.vm.provider "docker" do |d|
      d.name = "activator"
      d.image = "duncan/activator"
      d.ports = ["8888:8889"]
      d.vagrant_vagrantfile = "./proxy.Vagrantfile"
    end
  end

end
